import { JSX, SVGProps } from 'react'

import {
  ArrowLeft,
  ArrowRight,
  Atom,
  Blend,
  Blocks,
  BookOpenText,
  Box,
  Boxes,
  Check,
  CheckCircle,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ChevronsDown,
  ChevronsLeft,
  ChevronsRight,
  ChevronsUp,
  CircleAlert,
  CircleUser,
  Code,
  Component,
  Copy,
  CopyCheck,
  CreditCard,
  Ellipsis,
  ExternalLink,
  Eye,
  EyeOff,
  FileCode,
  Film,
  Globe,
  Info,
  KeyRound,
  Layers,
  Leaf,
  Link,
  ListChevronsDownUp,
  ListChevronsUpDown,
  LockKeyhole,
  LogIn,
  Mail,
  Menu,
  MessageCircleQuestionMark,
  Newspaper,
  Orbit,
  Package,
  Paintbrush,
  PanelLeftOpen,
  PanelRightOpen,
  Plug,
  Receipt,
  RectangleCircle,
  Rss,
  ScreenShare,
  Search,
  SearchX,
  Settings,
  Shapes,
  Share2,
  ShieldCheck,
  Star,
  TabletSmartphone,
  TreePine,
  TriangleAlert,
  User,
  Users,
  UserPlus,
  X,
  Zap,
} from 'lucide-react'

import { IconName } from 'lib/definitions'

export const ICONS: Record<IconName, any> = {
  'arrow-left': ArrowLeft,
  'arrow-right': ArrowRight,
  atom: Atom,
  blend: Blend,
  blocks: Blocks,
  'book-open-text': BookOpenText,
  box: Box,
  boxes: Boxes,
  check: Check,
  'check-circle': CheckCircle,
  'chevron-down': ChevronDown,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevron-up': ChevronUp,
  'chevrons-down': ChevronsDown,
  'chevrons-left': ChevronsLeft,
  'chevrons-right': ChevronsRight,
  'chevrons-up': ChevronsUp,
  'circle-alert': CircleAlert,
  'circle-user': CircleUser,
  close: X,
  code: Code,
  component: Component,
  copy: Copy,
  'copy-check': CopyCheck,
  'credit-card': CreditCard,
  ellipsis: Ellipsis,
  'external-link': ExternalLink,
  eye: Eye,
  'eye-off': EyeOff,
  'file-code': FileCode,
  film: Film,
  globe: Globe,
  info: Info,
  'key-round': KeyRound,
  layers: Layers,
  leaf: Leaf,
  link: Link,
  'list-chevrons-down-up': ListChevronsDownUp,
  'list-chevrons-up-down': ListChevronsUpDown,
  'lock-keyhole': LockKeyhole,
  'log-in': LogIn,
  mail: Mail,
  menu: Menu,
  'message-circle-question-mark': MessageCircleQuestionMark,
  newspaper: Newspaper,
  orbit: Orbit,
  package: Package,
  paintbrush: Paintbrush,
  'panel-left-open': PanelLeftOpen,
  'panel-right-open': PanelRightOpen,
  plug: Plug,
  receipt: Receipt,
  rectangleCircle: RectangleCircle,
  rss: Rss,
  'screen-share': ScreenShare,
  search: Search,
  'search-x': SearchX,
  settings: Settings,
  shapes: Shapes,
  'share-2': Share2,
  'shield-check': ShieldCheck,
  star: Star,
  'tablet-smartphone': TabletSmartphone,
  'tree-pine': TreePine,
  'triangle-alert': TriangleAlert,
  user: User,
  users: Users,
  'user-plus': UserPlus,
  zap: Zap,
}

export const getSvgIconComponent = (name: IconName): ((props: SVGProps<SVGElement>) => JSX.Element) => {
  return ICONS[name]
}
