services:
  neb-app:
    container_name: neb-app
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - PAT=$PAT
    ports:
      - 5173:5173
    environment:
      - NODE_ENV=$NODE_ENV
      - API_URL=$API_URL
      - VITE_PLAUSIBLE_DOMAIN=$VITE_PLAUSIBLE_DOMAIN
    networks:
      - shared
networks:
  shared:
    name: neb-net
