FROM node:20-alpine AS builder
WORKDIR /app

ARG PAT
ENV PAT=$PAT

RUN corepack enable && corepack use yarn@4.10.3

COPY package.json yarn.lock .yarnrc.yml ./
COPY .yarn/releases .yarn/releases
COPY .yarn/plugins .yarn/plugins
COPY .yarn/sdks .yarn/sdks
COPY .yarn/patches .yarn/patches
RUN yarn install --immutable

COPY . .
ENV NODE_ENV=production
RUN yarn build

FROM node:20-alpine AS runner
WORKDIR /app

RUN corepack enable && corepack use yarn@4.10.3

COPY package.json yarn.lock ./
RUN yarn install --immutable

COPY --from=builder /app/dist ./dist
COPY --from=builder /app/index.html ./index.html

ENV NODE_ENV=production
ENV NODE_OPTIONS=--enable-source-maps

CMD ["yarn", "start"]
