import type { BoxProps } from 'lib/components/core/Box'
import {
  BOX_BG_MODE,
  BOX_BG_ROLES,
  BOX_BORDER_MODE,
  BOX_BORDER_ROLES,
  BOX_COLORS,
  BOX_INTENTS,
  BOX_SURFACE_DEPTHS,
  BOX_TEXT,
  BOX_THEMES,
  DEFAULT_BOX_BG_MODE,
  DEFAULT_BOX_BG_ROLE,
  DEFAULT_BOX_BORDER_MODE,
  DEFAULT_BOX_BORDER_ROLE,
  DEFAULT_BOX_SURFACE_DEPTH,
  DEFAULT_BOX_TEXT,
} from 'lib/components/core/Box/constants'
import {
  CSS_ALIGN_CONTENT,
  CSS_ALIGN_ITEMS,
  CSS_ALIGN_SELF,
  CSS_CURSOR,
  CSS_DISPLAY,
  CSS_FLEX_DIRECTION,
  CSS_FLEX_WRAP,
  CSS_GRID_AUTO_FLOW,
  CSS_JUSTIFY_CONTENT,
  CSS_JUSTIFY_SELF,
  CSS_OVERFLOW,
  CSS_PLACE_CONTENT,
  CSS_PLACE_ITEMS,
  CSS_POINTER_EVENTS,
  CSS_POSITION,
  CSS_TEXT_ALIGN,
  CSS_VISIBILITY,
} from 'lib/constants'
import type { DocProp } from 'client/definitions'

export const BOX_PROPS: Record<keyof BoxProps, DocProp> = {
  // base
  children: {
    options: ['ReactNode'],
    description: 'Content rendered.',
    group: 'base',
  },
  tag: {
    options: ['HTML tag'],
    defaultValue: 'div',
    description: 'The HTML tag to be rendered as the container.',
    group: 'base',
  },
  tagRef: {
    options: ['RefObject'],
    description: 'Reference to the root HTML tag.',
    group: 'base',
  },
  tagAttrs: {
    options: ['HTML tag attributes'],
    description: 'Additional HTML attributes applied to the root tag.',
    group: 'base',
  },
  // surface
  theme: {
    options: BOX_THEMES,
    isResponsive: true,
    description:
      'Sets a local theme boundary for the component and its drawable descendants. Supports explicit themes, the global application theme or the opposite of the global application theme.',
    group: 'surface',
  },
  brand: {
    options: BOX_COLORS,
    description: 'Default surface color context for the component and its descendants.',
    group: 'surface',
  },
  drawable: {
    options: ['boolean'],
    description:
      'Enables visual rendering. When true, the Box can draw a surface using bg and intent. When false, it is structural and has no visual styling.',
    group: 'surface',
  },
  color: {
    options: BOX_COLORS,
    description: 'Color applied to the component.',
    group: 'surface',
  },
  intent: {
    options: BOX_INTENTS,
    description: "Color tone applied to the component's main color.",
    group: 'surface',
  },
  surfaceDepth: {
    options: BOX_SURFACE_DEPTHS,
    defaultValue: DEFAULT_BOX_SURFACE_DEPTH,
    description:
      "Selects which depth tier the component's surface color is drawn from - base or raised - each with its own per-intent lightness and interaction states.",
    group: 'surface',
  },
  bgMode: {
    options: BOX_BG_MODE,
    defaultValue: DEFAULT_BOX_BG_MODE,
    description:
      "Controls how the component's background is painted - transparent for no fill, tinted for a fill that blends with whatever sits behind it, or filled for a solid, full-strength fill.",
    group: 'surface',
  },
  bgRole: {
    options: BOX_BG_ROLES,
    defaultValue: DEFAULT_BOX_BG_ROLE,
    description:
      'Controls whether the background acts as a standard surface or as a selection, giving the component a highlighted, chosen look.',
    group: 'surface',
  },
  borderMode: {
    options: BOX_BORDER_MODE,
    defaultValue: DEFAULT_BOX_BORDER_MODE,
    description:
      "Controls how the component's border is painted - none for no border, tinted for a border that blends with whatever sits behind it, or filled for a solid, full-strength border.",
    group: 'surface',
  },
  borderRole: {
    options: BOX_BORDER_ROLES,
    defaultValue: DEFAULT_BOX_BORDER_ROLE,
    description:
      'Controls what the border is for - surface is the basic border, divider acts as a separator between items, and edge wraps the whole element as its outer boundary.',
    group: 'surface',
  },
  text: {
    options: BOX_TEXT,
    defaultValue: DEFAULT_BOX_TEXT,
    description:
      "Controls how the component's text color is resolved - default to inherit the surrounding text color, or colored to use the component's own intent/color.",
    group: 'surface',
  },
  // interaction
  interactive: {
    options: ['boolean'],
    description:
      'Enables visual interaction affordances such as hover and active styling. Sets drawable to true automatically.',
    group: 'interaction',
  },
  ripple: {
    options: ['boolean'],
    description: 'Toggles the ripple effect on pointer interaction.',
    group: 'interaction',
  },
  disabled: {
    options: ['boolean'],
    description: 'Disables the component and its interactions.',
    group: 'interaction',
  },
  activeOnFocus: {
    options: ['boolean'],
    description: 'Applies the active (pressed) visual state while the element is focused.',
    group: 'interaction',
  },
  cursor: {
    options: CSS_CURSOR,
    description: 'Controls the mouse cursor shown when hovering over the element.',
    group: 'interaction',
  },
  hidden: {
    options: ['boolean'],
    isResponsive: true,
    description: 'Controls whether the element is hidden and removed from layout.',
    group: 'interaction',
  },
  pointerEvents: {
    options: CSS_POINTER_EVENTS,
    description: 'Controls whether the element can receive pointer interactions.',
    link: true,
    group: 'interaction',
  },
  // layout
  display: {
    options: CSS_DISPLAY,
    isResponsive: true,
    description: 'Display type controlling how the component is laid out.',
    link: true,
    group: 'layout',
  },
  overflow: {
    options: CSS_OVERFLOW,
    isResponsive: true,
    description: 'Overflow behavior for both axes.',
    link: true,
    group: 'layout',
  },
  overflowX: {
    options: CSS_OVERFLOW,
    isResponsive: true,
    description: 'Overflow behavior on the horizontal axis.',
    link: true,
    group: 'layout',
  },
  overflowY: {
    options: CSS_OVERFLOW,
    isResponsive: true,
    description: 'Overflow behavior on the vertical axis.',
    link: true,
    group: 'layout',
  },
  position: {
    options: CSS_POSITION,
    isResponsive: true,
    description: 'Position in the layout flow.',
    link: true,
    group: 'layout',
  },
  inset: {
    options: ['string'],
    isResponsive: true,
    description:
      'Shorthand for setting top, right, bottom and left offsets. Directional props override it.',
    link: true,
    group: 'layout',
  },
  top: {
    options: ['string'],
    isResponsive: true,
    description: 'Top offset.',
    link: true,
    group: 'layout',
  },
  right: {
    options: ['string'],
    isResponsive: true,
    description: 'Right offset.',
    link: true,
    group: 'layout',
  },
  bottom: {
    options: ['string'],
    isResponsive: true,
    description: 'Bottom offset.',
    link: true,
    group: 'layout',
  },
  left: {
    options: ['string'],
    isResponsive: true,
    description: 'Left offset.',
    link: true,
    group: 'layout',
  },
  // appearance
  opacity: {
    options: ['string'],
    isResponsive: true,
    description: 'Transparency level, from fully visible to fully transparent.',
    link: true,
    group: 'appearance',
  },
  visibility: {
    options: Object.values(CSS_VISIBILITY),
    isResponsive: true,
    description: 'Controls whether the element is visible without affecting layout.',
    link: true,
    group: 'appearance',
  },
  textAlign: {
    options: CSS_TEXT_ALIGN,
    isResponsive: true,
    description: 'Text alignment within the component.',
    link: true,
    group: 'appearance',
  },
  aspectRatio: {
    options: ['string'],
    isResponsive: true,
    description: 'Defines the preferred width-to-height ratio of the component.',
    link: true,
    group: 'appearance',
  },
  transform: {
    options: ['string'],
    isResponsive: true,
    description: 'Applies a CSS transform for positional adjustment.',
    link: true,
    group: 'appearance',
  },
  zIndex: {
    options: ['number'],
    isResponsive: true,
    description: 'Controls the stacking order.',
    link: true,
    group: 'appearance',
  },
  // size
  blockSize: {
    options: ['string'],
    isResponsive: true,
    description: 'Logical height.',
    link: true,
    group: 'size',
  },
  minBlockSize: {
    options: ['string'],
    isResponsive: true,
    description: 'Minimum logical height.',
    link: true,
    group: 'size',
  },
  maxBlockSize: {
    options: ['string'],
    isResponsive: true,
    description: 'Maximum logical height.',
    link: true,
    group: 'size',
  },
  inlineSize: {
    options: ['string'],
    isResponsive: true,
    description: 'Logical width.',
    link: true,
    group: 'size',
  },
  minInlineSize: {
    options: ['string'],
    isResponsive: true,
    description: 'Minimum logical width.',
    link: true,
    group: 'size',
  },
  maxInlineSize: {
    options: ['string'],
    isResponsive: true,
    description: 'Maximum logical width.',
    link: true,
    group: 'size',
  },
  // padding
  padding: {
    options: ['string'],
    isResponsive: true,
    description: 'Padding for all sides.',
    link: true,
    group: 'padding',
  },
  paddingInline: {
    options: ['string'],
    isResponsive: true,
    description: 'Padding for the left and right sides.',
    link: true,
    group: 'padding',
  },
  paddingBlock: {
    options: ['string'],
    isResponsive: true,
    description: 'Padding for the top and bottom sides.',
    link: true,
    group: 'padding',
  },
  paddingTop: {
    options: ['string'],
    isResponsive: true,
    description: 'Padding for the top side.',
    link: true,
    group: 'padding',
  },
  paddingRight: {
    options: ['string'],
    isResponsive: true,
    description: 'Padding for the right side.',
    link: true,
    group: 'padding',
  },
  paddingBottom: {
    options: ['string'],
    isResponsive: true,
    description: 'Padding for the bottom side.',
    link: true,
    group: 'padding',
  },
  paddingLeft: {
    options: ['string'],
    isResponsive: true,
    description: 'Padding for the left side.',
    link: true,
    group: 'padding',
  },
  // margin
  margin: {
    options: ['string'],
    isResponsive: true,
    description: 'Margin for all sides.',
    link: true,
    group: 'margin',
  },
  marginInline: {
    options: ['string'],
    isResponsive: true,
    description: 'Margin for the left and right sides.',
    link: true,
    group: 'margin',
  },
  marginBlock: {
    options: ['string'],
    isResponsive: true,
    description: 'Margin for the top and bottom sides.',
    link: true,
    group: 'margin',
  },
  marginTop: {
    options: ['string'],
    isResponsive: true,
    description: 'Margin for the top side.',
    link: true,
    group: 'margin',
  },
  marginRight: {
    options: ['string'],
    isResponsive: true,
    description: 'Margin for the right side.',
    link: true,
    group: 'margin',
  },
  marginBottom: {
    options: ['string'],
    isResponsive: true,
    description: 'Margin for the bottom side.',
    link: true,
    group: 'margin',
  },
  marginLeft: {
    options: ['string'],
    isResponsive: true,
    description: 'Margin for the left side.',
    link: true,
    group: 'margin',
  },
  // border
  borderWidth: {
    options: ['string'],
    isResponsive: true,
    description: 'Sets border width overriding global value set by NebkitProvider.',
    link: true,
    group: 'border',
  },
  borderTopWidth: {
    options: ['string'],
    isResponsive: true,
    description: 'Border width for the top side.',
    link: true,
    group: 'border',
  },
  borderRightWidth: {
    options: ['string'],
    isResponsive: true,
    description: 'Border width for the right side.',
    link: true,
    group: 'border',
  },
  borderBottomWidth: {
    options: ['string'],
    isResponsive: true,
    description: 'Border width for the bottom side.',
    link: true,
    group: 'border',
  },
  borderLeftWidth: {
    options: ['string'],
    isResponsive: true,
    description: 'Border width for the left side.',
    link: true,
    group: 'border',
  },
  // border radius
  borderRadius: {
    options: ['string'],
    isResponsive: true,
    description: 'Sets border radius overriding global value set by NebkitProvider.',
    link: true,
    group: 'border radius',
  },
  borderTopLeftRadius: {
    options: ['string'],
    isResponsive: true,
    description: 'Border radius for the top left corner.',
    link: true,
    group: 'border radius',
  },
  borderTopRightRadius: {
    options: ['string'],
    isResponsive: true,
    description: 'Border radius for the top right corner.',
    link: true,
    group: 'border radius',
  },
  borderBottomRightRadius: {
    options: ['string'],
    isResponsive: true,
    description: 'Border radius for the bottom right corner.',
    link: true,
    group: 'border radius',
  },
  borderBottomLeftRadius: {
    options: ['string'],
    isResponsive: true,
    description: 'Border radius for the bottom left corner.',
    link: true,
    group: 'border radius',
  },
  // flex
  flexDirection: {
    options: CSS_FLEX_DIRECTION,
    isResponsive: true,
    description: 'Sets the flow of children along the main axis.',
    link: true,
    group: 'flex',
  },
  flexWrap: {
    options: CSS_FLEX_WRAP,
    isResponsive: true,
    description: 'Controls whether children stay on one line or wrap onto multiple lines.',
    link: true,
    group: 'flex',
  },
  justifyContent: {
    options: CSS_JUSTIFY_CONTENT,
    isResponsive: true,
    description: 'Distributes children along the main axis.',
    link: true,
    group: 'flex',
  },
  alignItems: {
    options: CSS_ALIGN_ITEMS,
    isResponsive: true,
    description: 'Aligns items within each row along the cross axis.',
    link: true,
    group: 'flex',
  },
  alignContent: {
    options: CSS_ALIGN_CONTENT,
    isResponsive: true,
    description: 'Aligns rows of items along the cross axis when wrapping is enabled.',
    link: true,
    group: 'flex',
  },
  gap: {
    options: ['string'],
    isResponsive: true,
    description: 'Defines spacing between children on both axes.',
    link: true,
    group: 'flex',
  },
  rowGap: {
    options: ['string'],
    isResponsive: true,
    description: 'Defines vertical spacing between rows of children.',
    link: true,
    group: 'flex',
  },
  columnGap: {
    options: ['string'],
    isResponsive: true,
    description: 'Defines horizontal spacing between columns of children.',
    link: true,
    group: 'flex',
  },
  flex: {
    options: ['string'],
    isResponsive: true,
    description: 'Shorthand for flex-grow, flex-shrink and flex-basis.',
    link: true,
    group: 'flex',
  },
  flexGrow: {
    options: ['string'],
    isResponsive: true,
    description:
      'Controls how much the item can grow relative to the other items when extra space is available.',
    link: true,
    group: 'flex',
  },
  flexShrink: {
    options: ['string'],
    isResponsive: true,
    description:
      'Controls how much the item can shrink relative to the other items when space is limited.',
    link: true,
    group: 'flex',
  },
  flexBasis: {
    options: ['string'],
    isResponsive: true,
    description: "Sets the item's initial main-size before free space is distributed.",
    link: true,
    group: 'flex',
  },
  alignSelf: {
    options: CSS_ALIGN_SELF,
    isResponsive: true,
    description:
      "Overrides the parent container's alignItems value for this specific item, in a flex or grid container.",
    link: true,
    group: 'flex',
  },
  order: {
    options: ['string'],
    isResponsive: true,
    description: "Defines the item's order relative to other items, independent of source order.",
    link: true,
    group: 'flex',
  },
  // grid
  gridTemplateColumns: {
    options: ['string'],
    isResponsive: true,
    description: 'Defines the column structure of the grid.',
    link: true,
    group: 'grid',
  },
  gridTemplateRows: {
    options: ['string'],
    isResponsive: true,
    description: "Sets how the grid's rows are laid out.",
    link: true,
    group: 'grid',
  },
  gridAutoRows: {
    options: ['string'],
    isResponsive: true,
    description: 'Defines the size of rows that are created automatically.',
    link: true,
    group: 'grid',
  },
  gridAutoColumns: {
    options: ['string'],
    isResponsive: true,
    description: 'Defines the size of columns that are created automatically.',
    link: true,
    group: 'grid',
  },
  gridAutoFlow: {
    options: CSS_GRID_AUTO_FLOW,
    isResponsive: true,
    description: 'Controls how items are automatically placed into the grid.',
    link: true,
    group: 'grid',
  },
  placeItems: {
    options: CSS_PLACE_ITEMS,
    isResponsive: true,
    description: 'Controls how grid items are aligned within their cells.',
    link: true,
    group: 'grid',
  },
  placeContent: {
    options: CSS_PLACE_CONTENT,
    isResponsive: true,
    description: 'Controls how the grid as a whole is aligned within the container.',
    link: true,
    group: 'grid',
  },
  gridColumn: {
    options: ['string'],
    isResponsive: true,
    description: "Sets the item's horizontal position or span between grid columns.",
    link: true,
    group: 'grid',
  },
  gridRow: {
    options: ['string'],
    isResponsive: true,
    description: "Sets the item's vertical position or span between grid rows.",
    link: true,
    group: 'grid',
  },
  justifySelf: {
    options: CSS_JUSTIFY_SELF,
    isResponsive: true,
    description: 'Controls horizontal alignment of the item within its grid cell.',
    link: true,
    group: 'grid',
  },
}
