export enum PROP_GROUPS {
  SURFACE = 'Surface',
  INTERACTION = 'Interaction',
  APPEARANCE = 'Appearance',
  LAYOUT = 'Layout',
  SIZE = 'Size',
  PADDING = 'Padding',
  MARGIN = 'Margin',
  BORDER = 'Border',
  BORDER_RADIUS = 'Border radius',
  ROOT = 'Root',
  FLEX_BOX = 'Flexbox',
  GRID_LAYOUT = 'Grid layout',
  IMAGE_RENDERING = 'Image rendering',
  TYPOGRAPHY = 'Typography',
  ICON = 'Icon',
  FLOATING = 'Floating',
  TOOLTIP = 'Tooltip',
  STATE = 'State',
}
