import { ICON_NAMES } from 'lib/definitions'

import { PlaygroundProp } from './types'

export const PLAYGROUND_CONTROLS_MAP: Record<PlaygroundProp, { type: 'array' | 'boolean' | 'string' }> = {
  active: { type: 'boolean' },
  blockSize: { type: 'string' },
  bold: { type: 'boolean' },
  borderRadius: { type: 'string' },
  borderWidth: { type: 'string' },
  brand: { type: 'array' },
  centered: { type: 'boolean' },
  checked: { type: 'boolean' },
  children: { type: 'string' },
  clampLines: { type: 'string' },
  color: { type: 'array' },
  content: { type: 'string' },
  description: { type: 'string' },
  disabled: { type: 'boolean' },
  drawable: { type: 'boolean' },
  dropdownPlacement: { type: 'array' },
  elevated: { type: 'boolean' },
  flexDirection: { type: 'array' },
  fontSize: { type: 'string' },
  fullWidth: { type: 'boolean' },
  heading: { type: 'string' },
  headingIntent: { type: 'array' },
  iconAngle: { type: 'string' },
  iconName: { type: 'array' },
  iconPlacement: { type: 'array' },
  initials: { type: 'string' },
  inlineSize: { type: 'string' },
  intent: { type: 'array' },
  interactive: { type: 'boolean' },
  italic: { type: 'boolean' },
  justifyContent: { type: 'array' },
  label: { type: 'string' },
  layout: { type: 'array' },
  lineHeight: { type: 'string' },
  loading: { type: 'boolean' },
  margin: { type: 'string' },
  maxInlineSize: { type: 'string' },
  minInlineSize: { type: 'string' },
  name: { type: 'array' },
  noWrap: { type: 'boolean' },
  padding: { type: 'string' },
  paddingBlock: { type: 'string' },
  paddingInline: { type: 'string' },
  placeholder: { type: 'string' },
  readOnly: { type: 'boolean' },
  ripple: { type: 'boolean' },
  scrollAlign: { type: 'array' },
  selected: { type: 'boolean' },
  shape: { type: 'array' },
  size: { type: 'array' },
  src: { type: 'string' },
  staticLabel: { type: 'string' },
  status: { type: 'array' },
  surface: { type: 'array' },
  textAlign: { type: 'array' },
  theme: { type: 'array' },
  truncate: { type: 'boolean' },
  typography: { type: 'array' },
  underline: { type: 'boolean' },
  variant: { type: 'array' },
  visibility: { type: 'array' },
  visibleItemsCount: { type: 'string' },
}

export const PLAYGROUND_ARRAY_DATA_MAP: Record<string, readonly string[]> = {
  IconName: ICON_NAMES,
}
