import { ComponentRef, ElementType, RefObject, useLayoutEffect } from 'react'

import { resolveLengthValue } from 'lib/helpers'
import { useScreen } from 'lib/hooks'
import { BoxProps } from 'lib/index.core'
import { syncRespStyle } from 'lib/internals/dom'

export const useSyncBoxRespStyle = <T extends ElementType = 'div'>({
  finalRef,
  //
  opacity,
  visibility,
  textAlign,
  zIndex,
  aspectRatio,
  transform,
  borderWidth,
  borderTopWidth,
  borderRightWidth,
  borderBottomWidth,
  borderLeftWidth,
  borderRadius,
  borderTopLeftRadius,
  borderTopRightRadius,
  borderBottomRightRadius,
  borderBottomLeftRadius,
  display,
  overflow,
  overflowX,
  overflowY,
  position,
  inset,
  top,
  right,
  bottom,
  left,
  blockSize,
  minBlockSize,
  maxBlockSize,
  inlineSize,
  minInlineSize,
  maxInlineSize,
  padding,
  paddingInline,
  paddingBlock,
  paddingTop,
  paddingRight,
  paddingBottom,
  paddingLeft,
  margin,
  marginInline,
  marginBlock,
  marginTop,
  marginRight,
  marginBottom,
  marginLeft,
}: BoxProps<T> & { finalRef: RefObject<ComponentRef<T> | null> }) => {
  const { bp } = useScreen()

  useLayoutEffect(() => {
    syncRespStyle('Box', finalRef, bp, {
      opacity,
      visibility,
      textAlign,
      zIndex,
      aspectRatio,
      transform,
      borderWidth,
      borderTopWidth,
      borderRightWidth,
      borderBottomWidth,
      borderLeftWidth,
      borderRadius,
      borderTopLeftRadius,
      borderTopRightRadius,
      borderBottomRightRadius,
      borderBottomLeftRadius,
      display,
      overflow,
      overflowX,
      overflowY,
      position,
      inset: inset !== undefined ? resolveLengthValue(inset, 'shorthand') : undefined,
      top: top !== undefined ? resolveLengthValue(top) : undefined,
      right: right !== undefined ? resolveLengthValue(right) : undefined,
      bottom: bottom !== undefined ? resolveLengthValue(bottom) : undefined,
      left: left !== undefined ? resolveLengthValue(left) : undefined,
      blockSize: blockSize !== undefined ? resolveLengthValue(blockSize) : undefined,
      minBlockSize: minBlockSize !== undefined ? resolveLengthValue(minBlockSize) : undefined,
      maxBlockSize: maxBlockSize !== undefined ? resolveLengthValue(maxBlockSize) : undefined,
      inlineSize: inlineSize !== undefined ? resolveLengthValue(inlineSize) : undefined,
      minInlineSize: minInlineSize !== undefined ? resolveLengthValue(minInlineSize) : undefined,
      maxInlineSize: maxInlineSize !== undefined ? resolveLengthValue(maxInlineSize) : undefined,
      padding: padding !== undefined ? resolveLengthValue(padding) : undefined,
      paddingInline: paddingInline !== undefined ? resolveLengthValue(paddingInline) : undefined,
      paddingBlock: paddingBlock !== undefined ? resolveLengthValue(paddingBlock) : undefined,
      paddingTop: paddingTop !== undefined ? resolveLengthValue(paddingTop) : undefined,
      paddingRight: paddingRight !== undefined ? resolveLengthValue(paddingRight) : undefined,
      paddingBottom: paddingBottom !== undefined ? resolveLengthValue(paddingBottom) : undefined,
      paddingLeft: paddingLeft !== undefined ? resolveLengthValue(paddingLeft) : undefined,
      margin: margin !== undefined ? resolveLengthValue(margin, 'shorthand') : undefined,
      marginInline: marginInline !== undefined ? resolveLengthValue(marginInline) : undefined,
      marginBlock: marginBlock !== undefined ? resolveLengthValue(marginBlock) : undefined,
      marginTop: marginTop !== undefined ? resolveLengthValue(marginTop) : undefined,
      marginRight: marginRight !== undefined ? resolveLengthValue(marginRight) : undefined,
      marginBottom: marginBottom !== undefined ? resolveLengthValue(marginBottom) : undefined,
      marginLeft: marginLeft !== undefined ? resolveLengthValue(marginLeft) : undefined,
    })
  }, [
    bp,
    opacity,
    visibility,
    zIndex,
    aspectRatio,
    transform,
    textAlign,
    borderWidth,
    borderTopWidth,
    borderRightWidth,
    borderBottomWidth,
    borderLeftWidth,
    borderRadius,
    borderTopLeftRadius,
    borderTopRightRadius,
    borderBottomRightRadius,
    borderBottomLeftRadius,
    display,
    overflow,
    overflowX,
    overflowY,
    position,
    inset,
    top,
    right,
    bottom,
    left,
    blockSize,
    minBlockSize,
    maxBlockSize,
    inlineSize,
    minInlineSize,
    maxInlineSize,
    padding,
    paddingInline,
    paddingBlock,
    paddingTop,
    paddingRight,
    paddingBottom,
    paddingLeft,
    margin,
    marginInline,
    marginBlock,
    marginTop,
    marginRight,
    marginBottom,
    marginLeft,
  ])
}
