export enum PageKey {
  home = '/home',
  foundations = '/foundations',
  core = '/core',
  pro = '/pro',
  faq = '/faq',
  pricing = '/pricing',
  pricingCore = '/pricing/core',
  pricingPro = '/pricing/pro',
  authLogin = '/auth/login',
  authRegister = '/auth/register',
  authRecover = '/auth/recover',
  profileAccount = '/profile/account',
  profileSettings = '/profile/settings',
  confirmAction = '/confirm-action',
}
