export enum PageKey {
  authLogin = '/auth/log-in',
  authRecover = '/auth/recover',
  authRegister = '/auth/register',
  confirmAction = '/confirm-action',
  core = '/core',
  faq = '/faq',
  feedback = '/feedback',
  foundations = '/foundations',
  home = '/home',
  playground = '/playground',
  pricing = '/pricing',
  pricingCore = '/pricing/core',
  pricingPro = '/pricing/pro',
  pro = '/pro',
  profileAccount = '/profile/account',
  profileSettings = '/profile/settings',
}
