export enum RoutingCategoryKey {
  controls = 'controls',
  elements = 'elements',
  form = 'form',
  gettingStarted = 'getting-started',
  layout = 'layout',
  navigation = 'navigation',
  overview = 'overview',
  primitives = 'primitives',
  utility = 'utility',
}

export enum RoutingItemKey {
  appFrame = 'app-frame',
  appNavBar = 'app-nav-bar',
  box = 'box',
  breadcrumb = 'breadcrumb',
  button = 'button',
  divider = 'divider',
  flex = 'flex',
  flow = 'flow',
  foundations = 'foundations',
  grid = 'grid',
  hAlign = 'h-align',
  hStack = 'h-stack',
  iconButton = 'icon-button',
  installation = 'installation',
  nebKitProvider = 'neb-kit-provider',
  pageNavLayout = 'page-nav-layout',
  pageSideNav = 'page-side-nav',
  select = 'select',
  spacer = 'spacer',
  stack = 'stack',
  svgIcon = 'svg-icon',
  table = 'table',
  text = 'text',
  vStack = 'v-stack',
  withIcon = 'with-icon',
}
