name: Main

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.18.0]

    env:
      PAT: ${{ secrets.PAT }}

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Enable Corepack and pin Yarn
        run: |
          corepack enable
          corepack use yarn@4.10.3

      - name: Prep Yarn cache folder
        run: mkdir -p .yarn/cache

      - name: Cache Yarn artifacts
        uses: actions/cache@v4
        with:
          path: .yarn/cache
          key: yarn-cache-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-cache-

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run prettier
        run: yarn prettier

      - name: Run linter
        run: yarn lint

      - name: Check circular dependencies
        run: yarn circular

      - name: Run typecheck
        run: yarn typecheck

      - name: Run TSD tests
        run: yarn tsd

      - name: Run Vitest tests
        run: yarn test

      - name: Run Playwright tests
        run: yarn pw
